name: TimerFuturiste
options:
  minimumXcodeGenVersion: 2.38.0
  xcodeVersion: "15.0"
  deploymentTarget:
    iOS: "16.1"
  createIntermediateGroups: true
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.tylian.timerfuturiste
    SWIFT_VERSION: 5.10
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
packages: {}
targets:
  TimerFuturiste:
    type: application
    platform: iOS
    deploymentTarget: "16.1"
    info:
      path: Sources/TimerFuturiste/Info.plist
    sources:
      - path: Sources/TimerFuturiste
      - path: Shared/LiveActivity
    settings:
      base:
        LSApplicationCategoryType: public.app-category.productivity
    dependencies:
      - target: TimerFuturisteLiveActivityExtension
        embed: true
    scheme:
      testTargets:
        - TimerFuturisteTests
        - TimerFuturisteUITests
      gatherCoverageData: true
      environmentVariables:
        UI_TESTING: YES
  TimerFuturisteLiveActivityExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.1"
    info:
      path: Sources/TimerFuturisteLiveActivityExtension/Info.plist
    sources:
      - path: Sources/TimerFuturisteLiveActivityExtension
      - path: Shared/LiveActivity
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tylian.timerfuturiste.liveactivity
        SKIP_INSTALL: YES
    dependencies:
      - sdk: ActivityKit.framework
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
  TimerFuturisteTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.1"
    sources:
      - path: Tests/TimerFuturisteTests
      - path: Shared/LiveActivity
    dependencies:
      - target: TimerFuturiste
  TimerFuturisteUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.1"
    sources:
      - path: Tests/TimerFuturisteUITests
    dependencies:
      - target: TimerFuturiste
